const PRODUCT_REQUEST ="PRODUCT_REQUEST"
const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
const PRODUCT_FAIL  = "PRODUCT_FAIL"
const CLEAR_ERRORS = "CLEAR_ERRORS"

export {PRODUCT_REQUEST,PRODUCT_SUCCESS,PRODUCT_FAIL,CLEAR_ERRORS}